script: "bundle exec rake test"
rvm:
  - rbx-18mode
  - rbx-19mode
  - jruby-19mode
  - jruby-18mode
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ree
gemfile:
  - gemfiles/Gemfile.rails-3.1.x
  - Gemfile
notifications:
  recipients:
    - parndt@gmail.com
